[WIP]Add ownership mechanism for a fixed-ip to record containers holding it
projecteru2/barrel pull request #23
Opened 2021-05-23 19:42 UTC by nyanpassu

This PR is to introduce a mechanism to record containers for a fixed-ip which is borrowed by these container

What I did
1. Add a field called attr on fixed-ip meta, the field is descibled as below
```json
{
  "Attrs": {
    "Borrows": [
      {
        "ID": "ec07",
        "HostName": "dev-100.10.1.1",
      }
    ]
  }
}
```
2. When created a container which uses fixed-ip, record it on the attr of fixed-ip
3. When removing a container, remove the record of it on the attr of fixed-ip
4. Only when a fixed-ip has no borrowing, we can release it

- Verification
1. Created a fixed-ip container via barrel, and then start it
2. Stop the fixed-ip
3. Create another fixed-ip container, and declare the same ip the previous container uses.
4. Start the second container
5. Remove the first container, the fixed-ip should not be released
6. Stop and remove the second container, the fixed-ip should be released

2021-06-15 06:02 UTC, CMGS requested changes

2021-06-15 06:02 UTC, CMGS commented on vessel/fixedippool_test.go
> -	"github.com/stretchr/testify/mock"
覆盖率只准增高不准降低的啊

2021-06-15 06:02 UTC, CMGS commented on vessel/fixedippool.go
> +// func (impl FixedIPAllocatorImpl) allocFixedIP(ctx context.Context, ip types.IP, codec *codec.IPInfoCodec) error {
WTF

2021-06-15 06:02 UTC, CMGS commented on vessel/fixedippool.go
> +}
你在写 go 不是写 java ！！！

2021-06-15 06:12 UTC, nyanpassu commented on store/store.go
> +	ErrKVNotExists = errors.New("KV not exists")
就是错误都丢到types/error里我感觉好乱阿，我想把固定ip的错误丢在types/error里，其他子模块自己的错误就留在子模块里，不然错误治理起来要头大

2021-06-15 06:13 UTC, nyanpassu commented on utils/time.go
> +func Second(value int) time.Duration {
额，每次都time.Duration(val) * time.Second好麻烦

2021-06-15 06:13 UTC, nyanpassu commented on vessel/fixedippool_test.go
> -	"github.com/stretchr/testify/mock"
哦这部分的测试转移走了，全部在embed etcd test那个里面

2021-06-15 06:14 UTC, nyanpassu commented on vessel/fixedippool.go
> +// func (impl FixedIPAllocatorImpl) allocFixedIP(ctx context.Context, ip types.IP, codec *codec.IPInfoCodec) error {
这部分忘记删掉了，稍后我push一下把这里删掉

2021-06-15 06:15 UTC, nyanpassu commented on vessel/fixedippool.go
> +}
我错了 QAQ

2021-06-15 06:17 UTC, nyanpassu commented on utils/context.go
> +package utils
这个是把logger.Entry丢在context里传递，这样被调用方可以在同一个log上下文里面打印log，减少函数传递的参数。这个用法类似containerd里面的namespace context。

2021-06-15 06:21 UTC, nyanpassu commented on app/app.go
> +	barrelEtcd "github.com/projecteru2/barrel/etcd"
barrelEtcd是提供embed etcd用来进行测试。里面有一个etcd.KV的实现，这个KV实现可以包含在一个lease范围内。测试的时候可以把用例局限在一个lease内，子测试结束后可以cleanup掉自己测试的KV，这样隔离开所有子测试。因为embed etcd实际数据是写磁盘不是写内存的（没发现可以配置只写内存），所以测试中尽量只开一个embed etcd实例，减少磁盘写入。

2021-06-15 12:41 UTC, nyanpassu commented on app/app.go
> +	barrelEtcd "github.com/projecteru2/barrel/etcd"
已经更换成coreos/etcd/integration实现

2021-06-15 12:46 UTC, nyanpassu commented on vessel/fixedippool.go
> +// func (impl FixedIPAllocatorImpl) allocFixedIP(ctx context.Context, ip types.IP, codec *codec.IPInfoCodec) error {
已经删除

2021-06-15 13:07 UTC, nyanpassu commented on vessel/fixedippool.go
> +}
impl全部干掉了

2021-06-16 02:45 UTC, nyanpassu commented on utils/time.go
> +func Second(value int) time.Duration {
已经删除

2021-06-18 06:16 UTC, anrs commented on store/etcd/etcd.go
> +func (e *etcdStore) Get(ctx context.Context, codec store.Codec) error {
直觉上讲，codec 如果是编解码的封装，那么说明你有 json 有 yaml 有各种不同的数据格式？如果是这样的话，key(), SetVersion() 就不应该被封装到里面了，因为 key() / SetVersion() 跟数据编解码无关，编解码只跟 json/yaml/plain text  这样的 bytes 数据相关，key/version 都是编解码的上层逻辑了。所以，我觉得 Codec 名字不是很恰当。

2021-06-18 06:16 UTC, anrs commented on store/etcd/etcd.go
> +	if resp, err = e.cli.Get(ctx, codec.Key()); err != nil {
Key 应该是 Get 的参数更自然

2021-06-18 06:22 UTC, anrs commented on utils/context.go
> +package utils
通常只会有一个全局 log 上下文，你这里 log entry 被参数化，那是不是意味着会存在多个不同的 log 上下文？

2021-06-18 06:22 UTC, anrs commented on utils/os/os.go
> +	os "os"
alias  和真实的  pkg name 一样就没必要了吧

2021-06-18 06:25 UTC, anrs commented on vessel/agent.go
> +	logger := agent.logger("next")
这个 'next' 和上面的 'serve' logger 的区别是？以及我不理解为什么要不同？

2021-06-20 08:11 UTC, nyanpassu commented on utils/os/os.go
> +	os "os"
似乎是golint在save的时候某种原因搞的，已改

2021-06-20 08:12 UTC, nyanpassu commented on store/etcd/etcd.go
> +	if resp, err = e.cli.Get(ctx, codec.Key()); err != nil {
这里codec是一个整体，Get用Codec做参数，不使用单独的key参数，因为不保证store是kv实现

2021-06-20 08:13 UTC, nyanpassu commented on store/etcd/etcd.go
> +func (e *etcdStore) Get(ctx context.Context, codec store.Codec) error {
codec不是对应json/yaml的编解码而是store的格式

2021-06-20 08:17 UTC, nyanpassu commented on vessel/agent.go
> +	logger := agent.logger("next")
按receiver name/method name标记log事件的source，更直接地把日志事件对应到source code。

2021-06-20 08:24 UTC, nyanpassu commented on utils/context.go
> +package utils
log上下文会切换，切换的时候不会嵌套。

2021-06-22 15:05 UTC, CMGS approved these changes

2021-06-22 15:05 UTC, merged